export default  [
    'Administração',
    'Africanidade',
    'Arte',
    'Auto-ajuda',
    'Biografia',
    'Ciências da Natureza',
    'Contos',
    'Cordel',
    'Cultura Indígena',
    'Dicionários',
    'Didáticos',
    'Direito',
    'Diversos',
    'Educação e didática',
    'Educação física',
    'Enciclopédias e revistas',
    'Espiritualidade',
    'Filosofia',
    'Geografia',
    'História',
    'Jornalismo',
    'Língua estrangeira',
    'Língua Portuguesa',
    'Literatura didática',
    'Literatura estrangeira',
    'Literatura infanto-juvenil',
    'Livros ilustrados',
    'Matemática',
    'Poemas',
    'Política e Economia',
    'Produção Textual',
    'Psicologia',
    'Quadrinhos',
    'Romance brasileiro',
    'Romance português',
    'Saúde',
    'Sociologia',
    'Teatro/Novela',
    'Tecnologia' ,
]