export default  [
    'Artes',
    'Biologia',
    'Educação Física',
    'Espanhol',
    'Filosofia',
    'Física',
    'Geografia',
    'Gramática',
    'História',
    'Inglês',
    'Literatura',
    'Matemática',
    'Música',
    'Química',
    'Redação',
    'Sociologia',
    'Teatro',
]